#!/usr/bin/env python3
"""Build the local original/Topaz/Arrow 2 cannon comparison page."""
import json
from pathlib import Path
out=Path(__file__).resolve().parents[1] / 'output/quiver-cannon/cannon-sequence'
m=json.loads((out/'manifest.json').read_text())
frames=[]
for r in m['records']:
    key=r['artwork_sha256']; source=r['source']
    frames.append(dict(cel=r['cel'], size=r['size'], original='cleaned/'+source, topaz='../../topaz-batch/4x/costumes/'+source, quiver='4x/'+key+'.png', svg='svg/'+key+'.svg', ready=(out/'4x'/f'{key}.png').exists()))
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Cannon · Arrow 2 comparison</title>
<style>body{margin:0;background:#151917;color:#f1ebd7;font:16px system-ui}main{max-width:1500px;margin:40px auto;padding:0 24px}h1{font:38px Georgia}p{color:#b8bfae}nav,header{display:flex;gap:16px;align-items:center;flex-wrap:wrap}button,select,a{color:inherit}button,select{font:inherit;background:#303a32;border:1px solid #77866e;border-radius:6px;padding:10px;cursor:pointer}.panels{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:24px 0}.art{height:340px;background:repeating-conic-gradient(#373b35 0% 25%,#30342f 0% 50%) 0/24px 24px;display:flex;align-items:center;justify-content:center;overflow:hidden}.art img{max-width:100%;max-height:100%;object-fit:contain}small{color:#b8bfae}h2{font-size:18px}.frames{display:flex;gap:8px;flex-wrap:wrap}.frames button[aria-current=true]{background:#77643c}@media(max-width:800px){.panels{grid-template-columns:1fr}.art{height:260px}}</style>
<main><header><h1>Cannon, redrawn</h1><a href="http://127.0.0.1:5200/#playtest">Open playtest</a></header><p>Original animation cels · Topaz Wonder 3.5 · Quiver Arrow 2. The game remains at 4×; SVG masters scale freely.</p><nav><button id="prev">← Previous</button><select id="select" aria-label="Frame"></select><button id="next">Next →</button><span id="size"></span></nav>
<section class="panels"><article><h2>Original</h2><div class="art"><img id="original" alt="Original cannon frame" style="image-rendering:pixelated"></div></article><article><h2>Topaz · Wonder 3.5, 4×</h2><div class="art"><img id="topaz" alt="Topaz cannon frame"></div></article><article><h2>Quiver · Arrow 2, 4×</h2><div class="art"><img id="quiver" alt="Quiver cannon frame"></div><p><a id="svg">Open SVG master</a></p></article></section><div class="frames" id="frames"></div><p><small>Frames are shown individually at their original canvas proportions. Tiny effect pieces are intentionally small sprites, not complete cannons. Reload this page as new outputs arrive.</small></p></main>
<script>const frames=DATA; let current=0; const selector=document.querySelector('#select');for(const f of frames){const o=new Option(`Frame ${f.cel}${f.ready?'':' · pending'}`,f.cel);selector.add(o);const b=document.createElement('button');b.textContent=f.cel;b.onclick=()=>show(f.cel);document.querySelector('#frames').append(b)}function show(i){current=(i+frames.length)%frames.length;const f=frames[current];selector.value=current;document.querySelector('#size').textContent=`${f.size.join(' × ')} source pixels`;for(const name of ['original','topaz','quiver']){const image=document.getElementById(name);image.src=f[name];image.style.width=`${f.size[0]*2}px`;image.style.height=`${f.size[1]*2}px`;image.style.visibility=name==='quiver'&&!f.ready?'hidden':'visible'}const svg=document.querySelector('#svg');svg.href=f.svg;svg.style.visibility=f.ready?'visible':'hidden';document.querySelectorAll('.frames button').forEach((b,i)=>b.setAttribute('aria-current',String(i===current)))}selector.onchange=()=>show(+selector.value);document.querySelector('#prev').onclick=()=>show(current-1);document.querySelector('#next').onclick=()=>show(current+1);show(0);</script></html>'''
(out/'index.html').write_text(html.replace('DATA',json.dumps(frames)))
